create table if not exists public.user_favorite_teams (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  team_key text not null check (char_length(team_key) between 1 and 120),
  team_name text not null check (char_length(team_name) between 1 and 120),
  api_football_team_id bigint,
  created_at timestamptz not null default now(),
  unique (user_id, team_key)
);

create table if not exists public.user_favorite_competitions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  competition_key text not null check (char_length(competition_key) between 1 and 120),
  competition_name text not null check (char_length(competition_name) between 1 and 120),
  api_football_league_id integer,
  created_at timestamptz not null default now(),
  unique (user_id, competition_key)
);

create table if not exists public.user_notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  reminder_24h boolean not null default true,
  reminder_1h boolean not null default true,
  kickoff_updates boolean not null default true,
  result_updates boolean not null default true,
  favorite_updates boolean not null default true,
  updated_at timestamptz not null default now()
);

create index if not exists user_favorite_teams_user_idx
  on public.user_favorite_teams(user_id, created_at desc);

create index if not exists user_favorite_competitions_user_idx
  on public.user_favorite_competitions(user_id, created_at desc);

alter table public.user_favorite_teams enable row level security;
alter table public.user_favorite_competitions enable row level security;
alter table public.user_notification_preferences enable row level security;

drop policy if exists "favorite_teams_own_rows" on public.user_favorite_teams;
create policy "favorite_teams_own_rows"
  on public.user_favorite_teams
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "favorite_competitions_own_rows" on public.user_favorite_competitions;
create policy "favorite_competitions_own_rows"
  on public.user_favorite_competitions
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "notification_preferences_own_rows" on public.user_notification_preferences;
create policy "notification_preferences_own_rows"
  on public.user_notification_preferences
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.user_favorite_teams to authenticated;
grant select, insert, update, delete on public.user_favorite_competitions to authenticated;
grant select, insert, update on public.user_notification_preferences to authenticated;
grant usage, select on sequence public.user_favorite_teams_id_seq to authenticated;
grant usage, select on sequence public.user_favorite_competitions_id_seq to authenticated;
