create extension if not exists pgcrypto with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  username text,
  avatar_url text,
  es_admin boolean not null default false,
  rol text not null default 'usuario',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_rol_check check (rol in ('usuario', 'admin'))
);

create table if not exists public.partidos (
  id bigint primary key,
  torneo text not null,
  fecha_texto text,
  fecha_orden timestamptz not null,
  local_nombre text not null,
  visitante_nombre text not null,
  local_corto text,
  visitante_corto text,
  -- Canonical stored value is en_vivo; UI labels may render it as "En vivo".
  estado text not null default 'proximo',
  goles_local_final integer,
  goles_visitante_final integer,
  api_football_fixture_id bigint,
  api_football_league_id integer,
  temporada integer,
  ronda text,
  minuto integer,
  payload_api jsonb not null default '{}'::jsonb,
  actualizado_api_en timestamptz,
  origen_datos text not null default 'manual',
  fuente_detalle text,
  creado_manual_en timestamptz,
  es_relevante boolean not null default false,
  prioridad_visual integer not null default 100,
  external_source text,
  external_id text,
  importado_externo_en timestamptz,
  raw_import_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint partidos_estado_check check (estado in ('proximo', 'en_vivo', 'finalizado', 'cancelado')),
  constraint partidos_goles_local_final_check check (goles_local_final is null or goles_local_final >= 0),
  constraint partidos_goles_visitante_final_check check (goles_visitante_final is null or goles_visitante_final >= 0),
  constraint partidos_prioridad_visual_check check (prioridad_visual >= 0),
  constraint partidos_api_football_fixture_id_key unique (api_football_fixture_id)
);

create table if not exists public.pronosticos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  partido_id bigint not null references public.partidos(id) on delete cascade,
  goles_local integer not null,
  goles_visitante integer not null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint pronosticos_marcador_local_check check (goles_local >= 0 and goles_local <= 99),
  constraint pronosticos_marcador_visitante_check check (goles_visitante >= 0 and goles_visitante <= 99),
  constraint pronosticos_partido_usuario_key unique (partido_id, usuario_id)
);

create table if not exists public.ligas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null check (char_length(trim(nombre)) >= 3),
  descripcion text,
  codigo text not null,
  creador_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ligas_codigo_key unique (codigo),
  constraint ligas_codigo_format_check check (codigo = upper(codigo) and char_length(codigo) between 6 and 20)
);

create table if not exists public.liga_miembros (
  id bigint generated by default as identity primary key,
  liga_id uuid not null references public.ligas(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  rol text not null default 'miembro',
  created_at timestamptz not null default now(),
  constraint liga_miembros_rol_check check (rol in ('owner', 'miembro')),
  constraint liga_miembros_liga_usuario_key unique (liga_id, usuario_id)
);

create index if not exists profiles_rol_idx
  on public.profiles(rol);

create index if not exists partidos_fecha_orden_idx
  on public.partidos(fecha_orden);

create index if not exists partidos_estado_fecha_idx
  on public.partidos(estado, fecha_orden);

create index if not exists partidos_local_fecha_idx
  on public.partidos(local_nombre, fecha_orden desc);

create index if not exists partidos_visitante_fecha_idx
  on public.partidos(visitante_nombre, fecha_orden desc);

create index if not exists partidos_torneo_fecha_idx
  on public.partidos(torneo, fecha_orden desc);

create index if not exists partidos_relevantes_fecha_idx
  on public.partidos(es_relevante, prioridad_visual, fecha_orden);

create unique index if not exists partidos_external_source_id_key
  on public.partidos(external_source, external_id)
  where external_source is not null
    and external_id is not null;

create index if not exists pronosticos_usuario_idx
  on public.pronosticos(usuario_id);

create index if not exists pronosticos_partido_idx
  on public.pronosticos(partido_id);

create index if not exists ligas_creador_idx
  on public.ligas(creador_id, created_at desc);

create index if not exists liga_miembros_usuario_idx
  on public.liga_miembros(usuario_id, created_at desc);

create index if not exists liga_miembros_liga_idx
  on public.liga_miembros(liga_id, created_at desc);

create or replace function public.predigol_handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nombre text;
begin
  v_nombre := nullif(trim(coalesce(new.raw_user_meta_data->>'nombre', '')), '');

  insert into public.profiles (id, nombre, rol, es_admin)
  values (
    new.id,
    coalesce(v_nombre, split_part(new.email, '@', 1), 'Hincha PrediGol'),
    'usuario',
    false
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists predigol_handle_new_user_profile_tg on auth.users;
create trigger predigol_handle_new_user_profile_tg
  after insert on auth.users
  for each row
  execute function public.predigol_handle_new_user_profile();

alter table public.profiles enable row level security;
alter table public.partidos enable row level security;
alter table public.pronosticos enable row level security;
alter table public.ligas enable row level security;
alter table public.liga_miembros enable row level security;

drop policy if exists "profiles_read_authenticated" on public.profiles;
create policy "profiles_read_authenticated"
  on public.profiles
  for select
  to authenticated
  using (true);

drop policy if exists "profiles_owner_insert" on public.profiles;
create policy "profiles_owner_insert"
  on public.profiles
  for insert
  to authenticated
  with check (id = auth.uid() and rol = 'usuario' and es_admin = false);

drop policy if exists "profiles_owner_update_safe" on public.profiles;
create policy "profiles_owner_update_safe"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid() and rol = 'usuario' and es_admin = false);

drop policy if exists "partidos_read_authenticated" on public.partidos;
create policy "partidos_read_authenticated"
  on public.partidos
  for select
  to authenticated
  using (true);

drop policy if exists "pronosticos_own_select" on public.pronosticos;
create policy "pronosticos_own_select"
  on public.pronosticos
  for select
  to authenticated
  using (usuario_id = auth.uid());

drop policy if exists "pronosticos_own_insert" on public.pronosticos;
create policy "pronosticos_own_insert"
  on public.pronosticos
  for insert
  to authenticated
  with check (usuario_id = auth.uid());

drop policy if exists "pronosticos_own_update" on public.pronosticos;
create policy "pronosticos_own_update"
  on public.pronosticos
  for update
  to authenticated
  using (usuario_id = auth.uid())
  with check (usuario_id = auth.uid());

drop policy if exists "ligas_read_authenticated" on public.ligas;
create policy "ligas_read_authenticated"
  on public.ligas
  for select
  to authenticated
  using (true);

drop policy if exists "ligas_owner_insert" on public.ligas;
create policy "ligas_owner_insert"
  on public.ligas
  for insert
  to authenticated
  with check (creador_id = auth.uid());

drop policy if exists "ligas_owner_update" on public.ligas;
create policy "ligas_owner_update"
  on public.ligas
  for update
  to authenticated
  using (creador_id = auth.uid())
  with check (creador_id = auth.uid());

drop policy if exists "liga_miembros_own_select" on public.liga_miembros;
create policy "liga_miembros_own_select"
  on public.liga_miembros
  for select
  to authenticated
  using (usuario_id = auth.uid());

drop policy if exists "liga_miembros_self_insert" on public.liga_miembros;
create policy "liga_miembros_self_insert"
  on public.liga_miembros
  for insert
  to authenticated
  with check (usuario_id = auth.uid());

drop policy if exists "liga_miembros_self_delete" on public.liga_miembros;
create policy "liga_miembros_self_delete"
  on public.liga_miembros
  for delete
  to authenticated
  using (usuario_id = auth.uid());

create or replace function public.obtener_mis_ligas()
returns table (
  id uuid,
  nombre text,
  descripcion text,
  codigo text,
  creador_id uuid,
  participantes bigint,
  es_miembro boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null and coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Debes iniciar sesion para consultar tus ligas.';
  end if;

  return query
  select
    l.id,
    l.nombre,
    l.descripcion,
    l.codigo,
    l.creador_id,
    count(lm_total.usuario_id)::bigint as participantes,
    true as es_miembro,
    l.created_at
  from public.ligas l
  join public.liga_miembros lm_self on lm_self.liga_id = l.id
  left join public.liga_miembros lm_total on lm_total.liga_id = l.id
  where coalesce(auth.role(), '') = 'service_role'
    or lm_self.usuario_id = auth.uid()
  group by l.id, l.nombre, l.descripcion, l.codigo, l.creador_id, l.created_at
  order by l.created_at desc;
end;
$$;

create or replace function public.obtener_detalle_liga(p_liga_id uuid)
returns table (
  id uuid,
  nombre text,
  descripcion text,
  codigo text,
  creador_id uuid,
  participantes bigint,
  es_miembro boolean,
  created_at timestamptz,
  miembros jsonb
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null and coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Debes iniciar sesion para consultar la liga.';
  end if;

  if coalesce(auth.role(), '') <> 'service_role'
    and not exists (
      select 1
      from public.liga_miembros lm
      where lm.liga_id = p_liga_id
        and lm.usuario_id = auth.uid()
    ) then
    raise exception 'No haces parte de esta liga.';
  end if;

  return query
  select
    l.id,
    l.nombre,
    l.descripcion,
    l.codigo,
    l.creador_id,
    count(lm.usuario_id)::bigint as participantes,
    true as es_miembro,
    l.created_at,
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'usuario_id', lm.usuario_id,
          'nombre', coalesce(nullif(trim(p.nombre), ''), 'Hincha PrediGol'),
          'username', p.username,
          'avatar_url', p.avatar_url,
          'rol', lm.rol,
          'created_at', lm.created_at
        )
        order by lm.created_at asc
      ) filter (where lm.usuario_id is not null),
      '[]'::jsonb
    ) as miembros
  from public.ligas l
  left join public.liga_miembros lm on lm.liga_id = l.id
  left join public.profiles p on p.id = lm.usuario_id
  where l.id = p_liga_id
  group by l.id, l.nombre, l.descripcion, l.codigo, l.creador_id, l.created_at;
end;
$$;

revoke all on public.profiles from anon;
revoke all on public.partidos from anon;
revoke all on public.pronosticos from anon;
revoke all on public.ligas from anon;
revoke all on public.liga_miembros from anon;

grant select, insert, update on public.profiles to authenticated;
grant select on public.partidos to authenticated;
grant select, insert, update on public.pronosticos to authenticated;
grant select, insert, update on public.ligas to authenticated;
grant select, insert, delete on public.liga_miembros to authenticated;

grant all on public.profiles to service_role;
grant all on public.partidos to service_role;
grant all on public.pronosticos to service_role;
grant all on public.ligas to service_role;
grant all on public.liga_miembros to service_role;

grant usage, select on sequence public.pronosticos_id_seq to authenticated;
grant usage, select on sequence public.liga_miembros_id_seq to authenticated;

revoke all on function public.predigol_handle_new_user_profile() from public, anon, authenticated;
revoke all on function public.obtener_mis_ligas() from public, anon, authenticated;
revoke all on function public.obtener_detalle_liga(uuid) from public, anon, authenticated;

grant execute on function public.obtener_mis_ligas() to authenticated, service_role;
grant execute on function public.obtener_detalle_liga(uuid) to authenticated, service_role;
