create extension if not exists pgcrypto with schema extensions;

alter table public.predigol_api_football_sync_config
  add column if not exists sync_secret text;

update public.predigol_api_football_sync_config
set sync_secret = encode(extensions.gen_random_bytes(32), 'hex')
where sync_secret is null;

alter table public.predigol_api_football_sync_config
  alter column sync_secret set not null;

revoke all on table public.predigol_api_football_sync_config
  from public, anon, authenticated;

create or replace function public.obtener_api_football_sync_config()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config public.predigol_api_football_sync_config%rowtype;
begin
  if not public.predigol_es_admin() then
    raise exception 'No tienes permiso para ver la sincronizacion de API-Football.';
  end if;

  select *
  into v_config
  from public.predigol_api_football_sync_config
  where id = 'default';

  return jsonb_build_object(
    'id', v_config.id,
    'enabled', v_config.enabled,
    'sync_upcoming', v_config.sync_upcoming,
    'sync_live', v_config.sync_live,
    'sync_results', v_config.sync_results,
    'season', v_config.season,
    'upcoming_limit', v_config.upcoming_limit,
    'updated_at', v_config.updated_at,
    'last_note', v_config.last_note
  );
end;
$$;

revoke all on function public.obtener_api_football_sync_config()
  from public, anon, authenticated;
grant execute on function public.obtener_api_football_sync_config()
  to authenticated, service_role;

create table if not exists public.api_football_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer,
  trigger_source text not null default 'manual'
    check (trigger_source in ('manual', 'pg_cron', 'unknown')),
  mode text not null
    check (mode in ('live', 'upcoming', 'results', 'range', 'all')),
  season integer,
  date_from date,
  date_to date,
  request_limit integer,
  status text not null default 'running'
    check (status in ('running', 'success', 'partial', 'error')),
  requests_count integer not null default 0,
  fixtures_count integer not null default 0,
  teams_count integer not null default 0,
  partidos_count integer not null default 0,
  live_snapshots_count integer not null default 0,
  skipped_count integer not null default 0,
  daily_limit integer,
  daily_remaining integer,
  minute_limit integer,
  minute_remaining integer,
  error_message text,
  result jsonb not null default '{}'::jsonb
);

create index if not exists api_football_sync_runs_started_at_idx
  on public.api_football_sync_runs(started_at desc);

create index if not exists api_football_sync_runs_status_started_idx
  on public.api_football_sync_runs(status, started_at desc);

alter table public.api_football_sync_runs enable row level security;

drop policy if exists "api_football_sync_runs_admin_read"
  on public.api_football_sync_runs;
create policy "api_football_sync_runs_admin_read"
  on public.api_football_sync_runs
  for select
  to authenticated
  using (public.predigol_es_admin());

grant select on public.api_football_sync_runs to authenticated;

create or replace function public.obtener_api_football_monitor()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
  v_runs jsonb;
  v_summary jsonb;
begin
  if not public.predigol_es_admin() then
    raise exception 'No tienes permiso para consultar el monitor de API-Football.';
  end if;

  select jsonb_build_object(
    'id', config.id,
    'enabled', config.enabled,
    'sync_upcoming', config.sync_upcoming,
    'sync_live', config.sync_live,
    'sync_results', config.sync_results,
    'season', config.season,
    'upcoming_limit', config.upcoming_limit,
    'updated_at', config.updated_at,
    'last_note', config.last_note
  )
  into v_config
  from public.predigol_api_football_sync_config config
  where config.id = 'default';

  select coalesce(jsonb_agg(to_jsonb(run) order by run.started_at desc), '[]'::jsonb)
  into v_runs
  from (
    select *
    from public.api_football_sync_runs
    order by started_at desc
    limit 12
  ) run;

  select jsonb_build_object(
    'runs_24h', count(*) filter (where started_at >= now() - interval '24 hours'),
    'requests_24h', coalesce(sum(requests_count) filter (
      where started_at >= now() - interval '24 hours'
    ), 0),
    'errors_24h', count(*) filter (
      where started_at >= now() - interval '24 hours' and status = 'error'
    ),
    'partials_24h', count(*) filter (
      where started_at >= now() - interval '24 hours' and status = 'partial'
    ),
    'last_success_at', max(finished_at) filter (where status = 'success')
  )
  into v_summary
  from public.api_football_sync_runs;

  return jsonb_build_object(
    'config', coalesce(v_config, '{}'::jsonb),
    'runs', coalesce(v_runs, '[]'::jsonb),
    'summary', coalesce(v_summary, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.obtener_api_football_monitor()
  from public, anon, authenticated;
grant execute on function public.obtener_api_football_monitor()
  to authenticated, service_role;

do $$
begin
  perform cron.unschedule('predigol-api-football-live-every-5-min');
exception
  when others then
    null;
end $$;

do $$
begin
  perform cron.unschedule('predigol-api-football-upcoming-hourly');
exception
  when others then
    null;
end $$;

do $$
begin
  perform cron.unschedule('predigol-api-football-results-hourly');
exception
  when others then
    null;
end $$;

select cron.schedule(
  'predigol-api-football-live-every-5-min',
  '*/5 * * * *',
  $$
  select net.http_post(
    url := 'https://aadkcyoyjxglrbiwfdgw.supabase.co/functions/v1/sync-live-fixtures?mode=live',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-sync-secret', sync_secret
    ),
    body := jsonb_build_object('trigger', 'pg_cron', 'mode', 'live', 'scheduled_at', now())
  )
  from public.predigol_api_football_sync_config
  where id = 'default'
    and enabled = true
    and sync_live = true;
  $$
);

select cron.schedule(
  'predigol-api-football-upcoming-hourly',
  '15 * * * *',
  $$
  select net.http_post(
    url := 'https://aadkcyoyjxglrbiwfdgw.supabase.co/functions/v1/sync-live-fixtures?mode=upcoming'
      || case when season is not null then '&season=' || season::text else '' end
      || '&limit=' || upcoming_limit::text,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-sync-secret', sync_secret
    ),
    body := jsonb_build_object('trigger', 'pg_cron', 'mode', 'upcoming', 'scheduled_at', now())
  )
  from public.predigol_api_football_sync_config
  where id = 'default'
    and enabled = true
    and sync_upcoming = true;
  $$
);

select cron.schedule(
  'predigol-api-football-results-hourly',
  '45 * * * *',
  $$
  select net.http_post(
    url := 'https://aadkcyoyjxglrbiwfdgw.supabase.co/functions/v1/sync-live-fixtures?mode=results'
      || case when season is not null then '&season=' || season::text else '' end
      || '&limit=' || upcoming_limit::text,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-sync-secret', sync_secret
    ),
    body := jsonb_build_object('trigger', 'pg_cron', 'mode', 'results', 'scheduled_at', now())
  )
  from public.predigol_api_football_sync_config
  where id = 'default'
    and enabled = true
    and sync_results = true;
  $$
);
