create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema extensions;

create table if not exists public.web_push_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null references public.web_push_subscriptions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  partido_id text,
  event_type text not null,
  sent_at timestamptz not null default now(),
  unique (subscription_id, event_key)
);

create index if not exists web_push_deliveries_user_time_idx
  on public.web_push_deliveries(user_id, sent_at desc);

alter table public.web_push_deliveries enable row level security;
grant select, insert, update, delete on public.web_push_deliveries to service_role;
grant usage, select on sequence public.web_push_deliveries_id_seq to service_role;

create table if not exists public.web_push_dispatch_config (
  id text primary key default 'default',
  enabled boolean not null default true,
  interval_minutes integer not null default 15 check (interval_minutes between 5 and 60),
  updated_at timestamptz not null default now()
);

insert into public.web_push_dispatch_config (id, enabled)
values ('default', true)
on conflict (id) do nothing;

alter table public.web_push_dispatch_config enable row level security;
grant select on public.web_push_dispatch_config to service_role;

do $$
begin
  perform cron.unschedule('predigol-web-push-every-15-min');
exception
  when others then
    null;
end $$;

select cron.schedule(
  'predigol-web-push-every-15-min',
  '*/15 * * * *',
  $$
  select net.http_post(
    url := 'https://aadkcyoyjxglrbiwfdgw.supabase.co/functions/v1/dispatch-push-notifications',
    headers := jsonb_build_object('Content-Type', 'application/json'),
    body := jsonb_build_object('trigger', 'pg_cron', 'scheduled_at', now())
  )
  from public.web_push_dispatch_config
  where id = 'default' and enabled = true;
  $$
);
