create table if not exists public.model_evaluations (
  id bigint generated by default as identity primary key,
  model_version text not null,
  evaluated_at timestamptz not null default now(),
  split_date timestamptz not null,
  training_matches integer not null check (training_matches > 0),
  test_matches integer not null check (test_matches > 0),
  outcome_accuracy numeric(7, 6) not null check (outcome_accuracy between 0 and 1),
  exact_score_accuracy numeric(7, 6) not null check (exact_score_accuracy between 0 and 1),
  home_goals_mae numeric(8, 6) not null check (home_goals_mae >= 0),
  away_goals_mae numeric(8, 6) not null check (away_goals_mae >= 0),
  brier_score numeric(8, 6) not null check (brier_score >= 0),
  log_loss numeric(8, 6) not null check (log_loss >= 0),
  baseline_outcome_accuracy numeric(7, 6) not null
    check (baseline_outcome_accuracy between 0 and 1),
  baseline_brier_score numeric(8, 6) not null check (baseline_brier_score >= 0),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists model_evaluations_version_date_idx
  on public.model_evaluations(model_version, evaluated_at desc);

alter table public.model_evaluations enable row level security;

drop policy if exists "model_evaluations_read_authenticated"
  on public.model_evaluations;
create policy "model_evaluations_read_authenticated"
  on public.model_evaluations
  for select
  to authenticated
  using (true);

grant select on public.model_evaluations to authenticated;
